//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetailsCorp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DetailsFirmEntities : DbContext
    {
        public DetailsFirmEntities()
            : base("name=DetailsFirmEntities")
        {
        }

        public static DetailsFirmEntities _context;

        public static DetailsFirmEntities GetContext()
        {
            if (_context == null)
                _context = new DetailsFirmEntities();

            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<PriceStory> PriceStory { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
