//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetailsCorp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int idSale { get; set; }
        public int SupplierID { get; set; }
        public int DetailID { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
        public Nullable<int> NumberDetails { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
